version: '2'
services:
  # airplay:
  #   build: ./airplay
  #   privileged: true
  #   restart: always
  #   labels:
  #     io.resin.features.kernel-modules: '1'
  #     io.resin.features.dbus: '1'
  #   network_mode: host

  broker:
    image: orbsmiv/mosquitto-rpi
    restart: always
    ports:
      - 1883:1883
      - 9001:9001

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
