version: '2'
services:
  broker:
    image: orbsmiv/mosquitto-rpi
    restart: always
    ports:
      - 1883:1883
      - 9001:9001

  debug:
    image: orbsmiv/mosquitto-rpi
    restart: always
    depends_on:
      - broker
    command: ["mosquitto_sub", "-h", "broker", "-t", "#"]

  rcswitch:
    build: ./rcswitch
    restart: always
    privileged: true
    depends_on:
      - broker

  homebridge:
    build: ./homebridge
    privileged: true
    restart: always
    labels:
      io.resin.features.dbus: '1'
    network_mode: host
    depends_on:
      - broker
    volumes:
      - 'homebridge:/data'

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80

volumes:
  homebridge:
