version: '2'
services:
  broker:
    image: orbsmiv/mosquitto-rpi
    restart: always
    ports:
      - 1883:1883
      - 9001:9001

  commander:
    build: ./commander
    restart: always
    depends_on:
      - broker
    volumes:
      - 'homebridge:/data/homebridge'

  debug:
    image: orbsmiv/mosquitto-rpi
    restart: always
    depends_on:
      - broker
    command: ["mosquitto_sub", "-h", "broker", "-t", "#", "-v"]
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d

  rcswitch:
    build: ./rcswitch
    restart: always
    privileged: true
    depends_on:
      - broker

  homebridge:
    build: ./homebridge
    privileged: true
    restart: always
    labels:
      io.resin.features.dbus: '1'
    network_mode: host
    depends_on:
      - broker
      - commander
    volumes:
      - 'homebridge:/data/homebridge'

  pihole:
    image: pihole/pihole:v4.0_aarch64
    restart: always
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80'
      - '443:443'
    environment:
      - ServerIP=10.0.0.10
      - TZ=Europe/Vienna
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - IPv6=False
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

volumes:
  homebridge:
  pihole:
  dnsmasq:
