version: '2'
services:
  airplay:
    build: ./airplay
    privileged: true
    restart: always
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.dbus: '1'
    ports:
      - 5000:5000
      - 5353:5353
      - 6001:6001
      - 6002:6002
      - 6003:6003
