version: '2'
services:
  broker:
    image: orbsmiv/mosquitto-rpi
    restart: always
    ports:
      - 1883:1883
      - 9001:9001

  homebridge:
    build: ./homebridge
    privileged: true
    restart: always
    labels:
      io.resin.features.dbus: '1'
    network_mode: host
    depends_on:
      - broker

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
